export const routes = {
  home: "/",
  draw: "/draw",
  collection: "/collection",
  echo: "/echo",
  friends: "/friends",
  profile: "/profile",
  agent: "/agent",
  onboarding: "/onboarding",
  login: "/login",
  register: "/register",

  colorBunnyLab: "/color-bunny-lab",
  colorPandaLab: "/color-panda-lab",
  colorOtterLab: "/color-otter-lab",
  colorOwlLab: "/color-owl-lab",
  colorDuckLab: "/color-duck-lab",
  colorBirdLab: "/color-bird-lab",
  colorGuineaPigLab: "/color-guinea-pig-lab",
  colorBearSingerLab: "/color-bear-singer-lab",
  colorCatLab: "/color-cat-lab",
  colorBlackCatLab: "/color-black-cat-lab",
  colorCoolWolfLab: "/color-cool-wolf-lab",
  colorDogCameraLab: "/color-dog-camera-lab",
  colorDogDrumLab: "/color-dog-drum-lab",
  colorKoalaLab: "/color-koala-lab",
  colorKarpyLab: "/color-karpy-lab",
  colorHamsterIcecreamLab: "/color-hamster-icecream-lab",
  colorDinoLab: "/color-dino-lab",
  colorDeerLab: "/color-deer-lab",
  colorPenguinLab: "/color-penguin-lab",
  colorSheepLab: "/color-sheep-lab",
  colorSlothLab: "/color-sloth-lab",
  colorFoxLab: "/color-fox-lab",
  colorRacoonLab: "/color-racoon-lab",
  colorSealLab: "/color-seal-lab",


} as const;
